# Setup
title:               Curie
tagline:             
description:         '<b href="https://github.com/Just-Curieous/Curie">Curie</b>: Toward Rigorous and Automated Scientific Experimentation with AI Agents'
url:                 http://Just-Curieous.github.io
baseurl:             ""
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Amber Liu
  url:               https://websites.umich.edu/~amberljc/
  email:             amberljc@umich.edu

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
