<<<<<<< HEAD
# Configurations
title:            Curie Blog
longtitle:        Toward Rigorous and Automated Scientific Experimentation with AI Agents
author:           Amber Liu
email:            amberljc@umich.edu 
=======
# Setup
title:               Curie
tagline:             ''
description:         '<a href="https://github.com/Just-Curieous/Curie">Curie</a>: Toward Rigorous and Automated Scientific Experimentation with AI Agents'
url:                 'https://just-curieous.github.io'
baseurl:             ''
paginate:            1
permalink:           pretty
>>>>>>> 814dcd769237a6d85e87afc7b21301a8bfb25d5e

version:          1.0
gitbook_version:  3.2.3

url:              'https://just-curieous.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     ./assets/gitbook/images/logo.jpg

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

<<<<<<< HEAD
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
=======
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - install.md

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
>>>>>>> 814dcd769237a6d85e87afc7b21301a8bfb25d5e
