# Setup
title:               Curie
tagline:             ''
description:         '<b href="https://github.com/Just-Curieous/Curie">Curie</b>: Toward Rigorous and Automated Scientific Experimentation with AI Agents'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
